# Сети
networks: #- не обязательна, но можно добавить настроек. Дефолтные сетки по умолчанию
    isolation-network:
      driver: bridge
services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container-portal_default
    ports:
        - "8180:80"
    volumes:
        - ./portal_cont:/var/www/html
        - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    extra_hosts:
      - "portal-docker.mysite.com:127.0.0.1"
    hostname: portal-docker.mysite.com
    domainname: portal-docker.mysite.com
    networks:
      - isolation-network
  php:
    build: ./build/php
    working_dir: /var/www/html
    volumes:
      - ./portal_cont/:/var/www/html/
      - ./build/php-ini/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    extra_hosts:
      - "portal-docker.mysite.com:172.20.0.1"
      # - "portal-docker.mysite.com:127.0.0.1"
    hostname: portal-docker.mysite.com
    domainname: mysite.com
    ports:
      - 9000:9000
    environment:
      - "DB_PORT=3307"
      - "DB_HOST=portal_mysite"
    networks:
      - isolation-network
  mysql:
    ports:
      - "3307:3307"
    build: './build/mysql'
    container_name: portal_mysite
    environment:
      MYSQL_ROOT_PASSWORD: "super-secret-password"
      MYSQL_DATABASE: "portal_mysite"
    volumes:
      - dbData:/var/lib/mysql
    networks:
      - isolation-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_portal
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=portal_mysite
    restart: always
    ports:
      - 8081:80
    networks:
      - isolation-network
volumes:
  app:
  dbData: